# Task 1

These are my solutions to task 1. The author is Cathal Donohoe (G00344919@gmit.ie)

One method of doing this task is with newtons method. This is the commented out sqrt function, but this will only print the float to a few places, not to 100. Therefore, i designed the sqrt2 function below.  

Firstly i declare the number 2 to be a variable. I then get the square root of this number by mulitplying it by the power of 1/2(0.5). I then quickly print it out to show that it worked correctly. I then create a googol. A googol is the large number 10 ** 100. I then mulitply the square root by a googol ** 2, this will move the value of squareroot to the left side of the decimal place to 100 places.  
Then i use a  while loop of when an empty variable(placeholder) is not equal to googol. The placeholder is then set to the value of the google. We then use floor divison, Floor division means after performing the division, results in the lower integer to the value. I then used a bitshift on the result of the floor division. The value for each bit in the binary representation of the input value is shifted to the left the number of bit positions specified by the second argument.  
When the while loop is done i cast the googol as a string to another variable. I then search that string  for the first instance of a '4'. This integer is the first number after the decimal place in the square root of 2, so before this integer, I insert a decimal place '.'. I then print out the edited string.

References:   
    [1] ps://www.educative.io/edpresso/floor-division (Even shows floor division in python)  
    [2] https://stackoverflow.com/questions/4022827/insert-some-string-into-given-string-at-given-index-in-python  
    [3] tour of Go: https://tour.golang.org/flowcontrol/8  
    [4] http://mathforum.org/library/drmath/view/65402.html  
    [5] http://resources.esri.com/help/9.3/arcgisengine/java/gp_toolref/spatial_analyst_tools/how_bitwise_left_shift_works.htm#:~:text=For%20each%20bit%20in%20the,farthest%20left%20bit%20is%20lost.
    [6] https://en.wikipedia.org/wiki/Googol  
    

In [1]:
#def sqrt(x):
    #"""
    #A function to calculate the square root of a number x
    #"""
    #Initial guess from square root of z
    #z = x/2
    #Loop until we're happy with the accuracy
    #while abs(x - (z * z)) > 0.00000001:
        #Claculate a better guess for the square root
    #    z -=(z*z -x) / (2*z)
    #Return the (approximate) sqaure root of x
    #return z

def sqrt2():
    #the number declared to a variable
    num = 2 
    #squares the number and sets it to a variable
    num_sqrt = num ** 0.5
    #prints the user input number and its square
    print('The square root of %0.3f is %0.3f'%(num ,num_sqrt))

    #create a googol(10^100)
    googol = 10**100
    #Mulitplying the square root by a googol**2 will move the value of squareroot to 100 places to the left side of the decimal place
    squareNum = num *(googol**2)
    #varaible used for accuracy
    placeHolder = 0
    
    #Loop to increase accuaracy
    while placeHolder != googol:
            #set placeholder to be the same as googol
            placeHolder = googol
            #get the square root and get the floor division
            #gets rid of the decimal
            googol = (placeHolder+(squareNum//placeHolder)) >> 1

    #cast googol as a string to a variable 
    square = str(googol)
    #search string for 4(first number after 1 in the square root of 2)
    index = square.find('4')
    #when found, edit index with a deciaml point before the index
    output_square = square[:index] + '.' + square[index:]
    #print full string
    print(output_square)

In [2]:
sqrt2()

The square root of 2.000 is 1.414
1.4142135623730950488016887242096980785696718753769480731766797379907324784621070388503875343276415727


# Task 2

Use Scipy.stats to varify 24.6 as being chi squared, and calculate the associated p value  
[1]: https://www.w3schools.com/python/python_lists.asp  
[2]: https://www.pythoncentral.io/the-difference-between-a-list-and-an-array/#:~:text=The%20main%20difference%20between%20a,you%20can%20perform%20to%20them.&text=It%20does%20take%20an%20extra,fine%20most%20of%20the%20time.  
[3]: https://stackoverflow.com/questions/39497519/easiest-way-to-make-data-frames-in-python-without-pandas-package  


In [3]:
import scipy.stats as stats

data = [[90, 60, 104, 95], [30, 50, 51, 20], [30,40,45,35]]

V, p, dof, expected = stats.chi2_contingency(data) 
print ("%.1f" %V)
print (p)
print (expected)

24.6
0.0004098425861096696
[[ 80.53846154  80.53846154 107.38461538  80.53846154]
 [ 34.84615385  34.84615385  46.46153846  34.84615385]
 [ 34.61538462  34.61538462  46.15384615  34.61538462]]
